sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t afrozjava/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true afrozjava/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'Docker'
  env: 'Docker-env-1'
  bucket_name: 'elasticbeanstalk-ap-south-1-246453948081'
  bucket_path: 'Docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
